# Generated by Django 2.0.2 on 2018-02-26 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('couleur_poils', models.CharField(max_length=255)),
                ('couleur_yeux', models.CharField(max_length=255)),
                ('sexe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=255)),
                ('prenom', models.TextField(max_length=255, null=True)),
                ('dateDeNaissance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Naissance')),
                ('sexe', models.CharField(max_length=1)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=255)),
                ('nom_race', models.CharField(max_length=255)),
                ('morphologie', models.CharField(max_length=255)),
                ('traits_comportementaux', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chien',
            name='proprio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogo.Proprietaire'),
        ),
        migrations.AddField(
            model_name='chien',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogo.Race'),
        ),
    ]
