# Generated by Django 2.0.2 on 2018-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chien',
            name='sexe',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='dateDeNaissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
