# Generated by Django 2.0.2 on 2018-03-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogo', '0002_auto_20180307_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='chien',
            name='mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfant_mere', to='dogo.Chien'),
        ),
        migrations.AddField(
            model_name='chien',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfant_pere', to='dogo.Chien'),
        ),
    ]
