# Generated by Django 2.0.2 on 2018-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogo', '0003_auto_20180308_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire',
            old_name='dateDeNaissance',
            new_name='date_naissance',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='nom_race',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='sexe',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='taille',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='traits_comportementaux',
            field=models.CharField(max_length=255),
        ),
    ]
