# Generated by Django 2.0.2 on 2018-03-29 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogo', '0006_auto_20180328_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
