# Generated by Django 2.0.2 on 2018-04-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogo', '0007_auto_20180329_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='traits_comportementaux',
            new_name='comportement',
        ),
        migrations.AlterField(
            model_name='chien',
            name='sexe',
            field=models.BooleanField(),
        ),
    ]
